/// Flutter icons Zanalys
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Zanalys
///      fonts:
///       - asset: fonts/Zanalys.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Zanalys {
  Zanalys._();

  static const _kFontFam = 'Zanalys';
  static const String? _kFontPkg = 'common';

  static const IconData heart =
      IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
